---

- hosts: all
  become: true
  tasks:

  - name: Install Updates for Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    
  - name: Install docker
    apt:
      name: docker.io
      state: latest

  - name: Enable docker
    service:
      name: docker
      state: restarted
      enabled: true

  - name: Start docker system
    service:
      name: docker
      state: started
      enabled: true

  - name: Add Docker to group
    command: sudo usermod -aG docker jefferson

  - name: Restarting docker
    command: sudo systemctl restart docker

  - name: create build directory
    file:
       path: ./root/demo-dockerfile
       state: directory
       owner: root
       group: root
       mode: '0755'

  - name: copy Dockerfile
    copy:
      src: ./Dockerfile
      dest: ./root/demo-dockerfile/Dockerfile
      owner: root
      group: root
      mode: '0644'

  - name: build container image
    docker_image:
      name: dockerr
      source: build
      build:
        path: ./root/demo-dockerfile
        args:
          listen_port: 8080
      state: present

  - name: access containerized app
    shell:
      docker run -it -d -p 8080:80 docker
